# Generated by Django 3.1.1 on 2020-10-08 13:46

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200929_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.get_user_directory_path),
        ),
    ]
