# Generated by Django 3.1.1 on 2020-10-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_auto_20201014_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='dropoff_address',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_address',
            field=models.CharField(max_length=60),
        ),
    ]
